#ifndef _CHECK_H
   #define _CHECK_H 1

/*----------------------------------------------------------------------------*/
/*                                                                            */
/*         FUNCION PARA INICIALIZAR LA MATRIZ DE CONTROL DEL CODIGO           */
/*                                                                            */
/*----------------------------------------------------------------------------*/

void InicializarCheck(Matriz *MatrizControl);

#endif
