#ifndef _MATRIZ_H
   #define _MATRIZ_H 1

/*----------------------------------------------------------------------------*/
/*                                                                            */
/*               FUNCION QUE MULTIPLICA MATRICES POR VECTORES                 */
/*                                                                            */
/*----------------------------------------------------------------------------*/

void MulMatVec(Matriz *Mat, int Vec[], int Res[]);

#endif
