#ifndef _DESCRIP_H
   #define _DESCRIP_H 1

/*----------------------------------------------------------------------------*/
/*                                                                            */
/*           FUNCION QUE DESCRIBE LA ACCION QUE REALIZA EL PROGRAMA           */
/*                                                                            */
/*----------------------------------------------------------------------------*/

void Descripcion(void);

#endif
