#ifndef _MEM_H
   #define _MEM_H 1

/*----------------------------------------------------------------------------*/
/*                                                                            */
/*               FUNCIONES PARA RESERVAR MEMORIA DINAMICAMENTE                */
/*                                                                            */
/*----------------------------------------------------------------------------*/

/* FUNCION QUE RESERVA MEMORIA PARA PALABRAS DEL CODIGO */

int ResMemCod(PalCod *Palabra);

#endif
