#ifndef _STRUCT_H
   #define _STRUCT_H 1

/*----------------------------------------------------------------------------*/
/*                                                                            */
/*                ESTRUCTURA DE DATOS PARA PALABRAS DEL CODIGO                */
/*                                                                            */
/*----------------------------------------------------------------------------*/

typedef struct {
   int intLong,
       *intPalabra;	
   } PalCod;

#endif
