#ifndef _IODAT_H
   #define _IODAT_H 1

/*----------------------------------------------------------------------------*/
/*                                                                            */
/*      FUNCION PARA RECOGER PALABRAS DEL CODIGO DESDE LA SALIDA ESTANDAR     */
/*                                                                            */
/*----------------------------------------------------------------------------*/

int LeerDato(PalCod *Palabra);

#endif
